/**
 * Toxic-link triage and Google disavow file generation, derived from the
 * Referring Domains rows already on the page. No extra DataForSEO call.
 *
 * The output format is Google's: one `domain:` line per site, `#` for comments.
 * Domain-level entries are the right granularity here — Google's own guidance
 * is to disavow at the domain level when a whole site is the problem, and the
 * referring-domain rows are already grouped that way.
 */

export type ToxicCandidateRow = {
  domain: string | null;
  backlinks: number | null;
  rank: number | null;
  spamScore: number | null;
};

export type ToxicCandidate = {
  domain: string;
  backlinks: number;
  rank: number | null;
  spamScore: number;
  /** Why this domain surfaced, shown in the table and the file comments. */
  reason: string;
};

export type ToxicAudit = {
  candidates: ToxicCandidate[];
  /** Backlinks accounted for by the flagged domains. */
  affectedBacklinks: number;
  /** Referring domains examined — the rows that carried a spam score. */
  scored: number;
  threshold: number;
};

/**
 * DataForSEO's spam score runs 0-100. Its own documentation treats scores above
 * roughly 60 as high risk, which is where this defaults; the caller can tighten
 * it. Nothing here disavows anything automatically — this only produces a file
 * for a human to review.
 */
export const DEFAULT_SPAM_THRESHOLD = 60;

export function auditToxicDomains(
  rows: ToxicCandidateRow[],
  threshold: number = DEFAULT_SPAM_THRESHOLD,
): ToxicAudit {
  const scored = rows.filter(
    (row) => row.spamScore != null && Number.isFinite(row.spamScore),
  );

  const candidates = scored
    .flatMap((row) => {
      const spamScore = row.spamScore;
      const domain = normalizeDisavowDomain(row.domain);
      if (spamScore == null || !domain || spamScore < threshold) return [];

      return [
        {
          domain,
          backlinks: row.backlinks ?? 0,
          rank: row.rank ?? null,
          spamScore,
          reason: describeReason(spamScore, row.rank ?? null),
        },
      ];
    })
    // Worst first, then by how many links are at stake, so the top of the list
    // is where a review should start.
    .toSorted(
      (a, b) =>
        b.spamScore - a.spamScore ||
        b.backlinks - a.backlinks ||
        a.domain.localeCompare(b.domain),
    );

  return {
    candidates,
    affectedBacklinks: candidates.reduce(
      (total, candidate) => total + candidate.backlinks,
      0,
    ),
    scored: scored.length,
    threshold,
  };
}

function describeReason(spamScore: number, rank: number | null): string {
  if (rank != null && rank <= 10) {
    return `Spam score ${spamScore}, and the domain itself has almost no authority (DR ${rank}).`;
  }
  return `Spam score ${spamScore}, above the ${spamScore >= 80 ? "severe" : "high"}-risk line.`;
}

/**
 * Google's disavow format: comments start with `#`, and a whole site is
 * excluded with `domain:example.com`. The file is capped at 100,000 lines and
 * 2 MB, which this never approaches from a single page of rows.
 */
export function buildDisavowFile(
  audit: ToxicAudit,
  target: string,
  generatedAt: Date,
): string {
  const lines = [
    `# Disavow candidates for ${target}`,
    `# Generated by FlyRocketSEO on ${generatedAt.toISOString().slice(0, 10)}`,
    `# ${audit.candidates.length} domain${audit.candidates.length === 1 ? "" : "s"} with a spam score of ${audit.threshold} or higher, covering ${audit.affectedBacklinks} backlink${audit.affectedBacklinks === 1 ? "" : "s"}.`,
    "#",
    "# Review every line before uploading. Disavowing a healthy link costs you",
    "# ranking, and Google treats this file as a last resort.",
    "",
  ];

  for (const candidate of audit.candidates) {
    lines.push(
      `# ${candidate.reason} ${candidate.backlinks} backlink${candidate.backlinks === 1 ? "" : "s"}.`,
    );
    lines.push(`domain:${candidate.domain}`);
  }

  return `${lines.join("\n")}\n`;
}

export function buildDisavowFilename(target: string): string {
  const normalized = target
    .toLowerCase()
    .trim()
    .replace(/https?:\/\//g, "")
    .replace(/[^a-z0-9.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);

  return `disavow${normalized ? `-${normalized}` : ""}.txt`;
}

/**
 * Strips scheme, `www.`, path and port so the line is the bare host Google
 * expects after `domain:`.
 */
export function normalizeDisavowDomain(
  value: string | null | undefined,
): string | null {
  const host = (value ?? "")
    .toLowerCase()
    .trim()
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0]
    .split(":")[0];

  return host.includes(".") ? host : null;
}
