import { describeSpamScore } from "@/client/lib/spamScore";

/**
 * Toxic-link triage and Google disavow file generation, derived from the
 * Referring Domains rows already on the page. No extra DataForSEO call.
 *
 * The output format is Google's: one `domain:` line per site, `#` for comments.
 * Domain-level entries are the right granularity here — Google's own guidance
 * is to disavow at the domain level when a whole site is the problem, and the
 * referring-domain rows are already grouped that way.
 */

export type ToxicCandidateRow = {
  domain: string | null;
  backlinks: number | null;
  rank: number | null;
  spamScore: number | null;
};

type ToxicCandidate = {
  domain: string;
  backlinks: number;
  rank: number | null;
  spamScore: number;
  /** Why this domain surfaced, shown in the table and the file comments. */
  reason: string;
};

type ToxicAudit = {
  candidates: ToxicCandidate[];
  /** Backlinks accounted for by the flagged domains. */
  affectedBacklinks: number;
  /** Referring domains examined — the rows that carried a spam score. */
  scored: number;
};

/**
 * Surfaces domains in the shared High-risk signal tier for human review.
 * Nothing here disavows anything automatically.
 */
export function auditToxicDomains(rows: ToxicCandidateRow[]): ToxicAudit {
  const scored = rows.filter(
    (row) => row.spamScore != null && Number.isFinite(row.spamScore),
  );

  const candidates = scored
    .flatMap((row) => {
      const spamScore = row.spamScore;
      const domain = normalizeDisavowDomain(row.domain);
      if (
        spamScore == null ||
        !domain ||
        describeSpamScore(spamScore).tier !== "high"
      ) {
        return [];
      }

      return [
        {
          domain,
          backlinks: row.backlinks ?? 0,
          rank: row.rank ?? null,
          spamScore,
          reason: describeReason(spamScore, row.rank ?? null),
        },
      ];
    })
    // Worst first, then by how many links are at stake, so the top of the list
    // is where a review should start.
    .toSorted(
      (a, b) =>
        b.spamScore - a.spamScore ||
        b.backlinks - a.backlinks ||
        a.domain.localeCompare(b.domain),
    );

  return {
    candidates,
    affectedBacklinks: candidates.reduce(
      (total, candidate) => total + candidate.backlinks,
      0,
    ),
    scored: scored.length,
  };
}

function describeReason(spamScore: number, rank: number | null): string {
  const spam = describeSpamScore(spamScore);
  if (rank != null && rank <= 10) {
    return `Spam score ${spam.formatted}/100 · ${spam.label}, and the domain itself has almost no authority (Domain authority ${rank}/100).`;
  }
  return `Spam score ${spam.formatted}/100 · ${spam.label}.`;
}

/**
 * Google's disavow format: comments start with `#`, and a whole site is
 * excluded with `domain:example.com`. The file is capped at 100,000 lines and
 * 2 MB, which this never approaches from a single page of rows.
 */
export function buildDisavowFile(
  audit: ToxicAudit,
  target: string,
  generatedAt: Date,
): string {
  const lines = [
    `# Disavow CANDIDATES for ${target} — not a finished disavow file.`,
    `# Generated by FlyRocketSEO on ${generatedAt.toISOString().slice(0, 10)}`,
    `# ${audit.candidates.length} domain${audit.candidates.length === 1 ? "" : "s"} fell in the High-risk signal tier, covering ${audit.affectedBacklinks} backlink${audit.affectedBacklinks === 1 ? "" : "s"}.`,
    "#",
    "# A third-party spam score is a starting point for a review, not evidence",
    "# that a link is artificial. Google intends this file for a substantial",
    "# number of links you know to be paid or manipulative, usually alongside a",
    "# manual action — not for everything a tool scores badly. A high-scoring",
    "# domain may well be a legitimate site.",
    "#",
    "# Open every line, look at the linking page, and delete the ones you would",
    "# be happy to keep. Disavowing a healthy link costs you ranking and is slow",
    "# to undo.",
    "",
  ];

  for (const candidate of audit.candidates) {
    lines.push(
      `# ${candidate.reason} ${candidate.backlinks} backlink${candidate.backlinks === 1 ? "" : "s"}.`,
    );
    lines.push(`domain:${candidate.domain}`);
  }

  return `${lines.join("\n")}\n`;
}

export function buildDisavowFilename(target: string): string {
  const normalized = target
    .toLowerCase()
    .trim()
    .replace(/https?:\/\//g, "")
    .replace(/[^a-z0-9.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);

  return `disavow${normalized ? `-${normalized}` : ""}.txt`;
}

/**
 * Strips scheme, `www.`, path and port so the line is the bare host Google
 * expects after `domain:`.
 */
export function normalizeDisavowDomain(
  value: string | null | undefined,
): string | null {
  const host = (value ?? "")
    .toLowerCase()
    .trim()
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0]
    .split(":")[0];

  return host.includes(".") ? host : null;
}
