import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { instrumentMcpToolHandler } from "@/server/mcp/instrumentation";
import {
  getAiSearchVolumeTool,
  getClickstreamVolumeTool,
  getGlobalVolumeTool,
  getKeywordTrendsTool,
} from "@/server/mcp/tools/trends-tools";
import {
  estimateDomainTrafficTool,
  findCompetitorsTool,
  getDomainRankHistoryTool,
  getKeywordDifficultyTool,
  getKeywordGapTool,
  getKeywordsForSiteTool,
  getSearchIntentTool,
  getSubdomainsTool,
} from "@/server/mcp/tools/competitor-research-tools";
import {
  findLinkCompetitorsTool,
  getBacklinkAnchorsTool,
  getLinkGapTool,
  getNewLostBacklinksTool,
  getSpamScoresTool,
} from "@/server/mcp/tools/backlinks-insights-tools";
import {
  getBusinessProfileTool,
  getBusinessReviewsTool,
} from "@/server/mcp/tools/local-seo-tools";
import {
  getBrandMentionSummaryTool,
  getBrandMentionTrendsTool,
  searchBrandMentionsTool,
} from "@/server/mcp/tools/brand-monitoring-tools";
import {
  getDomainTechnologiesTool,
  getDomainWhoisTool,
} from "@/server/mcp/tools/domain-analytics-tools";
import { auditPageTool } from "@/server/mcp/tools/onpage-tools";

// Competitor, backlink-insight, trends, and local SEO research tools, split
// from registerOpenSeoMcpTools to keep each registration function readable.
export function registerResearchExpansionTools(server: McpServer) {
  server.registerTool(
    findCompetitorsTool.name,
    findCompetitorsTool.config,
    instrumentMcpToolHandler(
      findCompetitorsTool.name,
      findCompetitorsTool.config.outputSchema,
      findCompetitorsTool.handler,
    ),
  );
  server.registerTool(
    getKeywordGapTool.name,
    getKeywordGapTool.config,
    instrumentMcpToolHandler(
      getKeywordGapTool.name,
      getKeywordGapTool.config.outputSchema,
      getKeywordGapTool.handler,
    ),
  );
  server.registerTool(
    getKeywordsForSiteTool.name,
    getKeywordsForSiteTool.config,
    instrumentMcpToolHandler(
      getKeywordsForSiteTool.name,
      getKeywordsForSiteTool.config.outputSchema,
      getKeywordsForSiteTool.handler,
    ),
  );
  server.registerTool(
    getKeywordDifficultyTool.name,
    getKeywordDifficultyTool.config,
    instrumentMcpToolHandler(
      getKeywordDifficultyTool.name,
      getKeywordDifficultyTool.config.outputSchema,
      getKeywordDifficultyTool.handler,
    ),
  );
  server.registerTool(
    getSearchIntentTool.name,
    getSearchIntentTool.config,
    instrumentMcpToolHandler(
      getSearchIntentTool.name,
      getSearchIntentTool.config.outputSchema,
      getSearchIntentTool.handler,
    ),
  );
  server.registerTool(
    estimateDomainTrafficTool.name,
    estimateDomainTrafficTool.config,
    instrumentMcpToolHandler(
      estimateDomainTrafficTool.name,
      estimateDomainTrafficTool.config.outputSchema,
      estimateDomainTrafficTool.handler,
    ),
  );
  server.registerTool(
    getDomainRankHistoryTool.name,
    getDomainRankHistoryTool.config,
    instrumentMcpToolHandler(
      getDomainRankHistoryTool.name,
      getDomainRankHistoryTool.config.outputSchema,
      getDomainRankHistoryTool.handler,
    ),
  );
  server.registerTool(
    getSubdomainsTool.name,
    getSubdomainsTool.config,
    instrumentMcpToolHandler(
      getSubdomainsTool.name,
      getSubdomainsTool.config.outputSchema,
      getSubdomainsTool.handler,
    ),
  );
  server.registerTool(
    getBacklinkAnchorsTool.name,
    getBacklinkAnchorsTool.config,
    instrumentMcpToolHandler(
      getBacklinkAnchorsTool.name,
      getBacklinkAnchorsTool.config.outputSchema,
      getBacklinkAnchorsTool.handler,
    ),
  );
  server.registerTool(
    findLinkCompetitorsTool.name,
    findLinkCompetitorsTool.config,
    instrumentMcpToolHandler(
      findLinkCompetitorsTool.name,
      findLinkCompetitorsTool.config.outputSchema,
      findLinkCompetitorsTool.handler,
    ),
  );
  server.registerTool(
    getLinkGapTool.name,
    getLinkGapTool.config,
    instrumentMcpToolHandler(
      getLinkGapTool.name,
      getLinkGapTool.config.outputSchema,
      getLinkGapTool.handler,
    ),
  );
  server.registerTool(
    getSpamScoresTool.name,
    getSpamScoresTool.config,
    instrumentMcpToolHandler(
      getSpamScoresTool.name,
      getSpamScoresTool.config.outputSchema,
      getSpamScoresTool.handler,
    ),
  );
  server.registerTool(
    getNewLostBacklinksTool.name,
    getNewLostBacklinksTool.config,
    instrumentMcpToolHandler(
      getNewLostBacklinksTool.name,
      getNewLostBacklinksTool.config.outputSchema,
      getNewLostBacklinksTool.handler,
    ),
  );
  server.registerTool(
    getKeywordTrendsTool.name,
    getKeywordTrendsTool.config,
    instrumentMcpToolHandler(
      getKeywordTrendsTool.name,
      getKeywordTrendsTool.config.outputSchema,
      getKeywordTrendsTool.handler,
    ),
  );
  server.registerTool(
    getClickstreamVolumeTool.name,
    getClickstreamVolumeTool.config,
    instrumentMcpToolHandler(
      getClickstreamVolumeTool.name,
      getClickstreamVolumeTool.config.outputSchema,
      getClickstreamVolumeTool.handler,
    ),
  );
  server.registerTool(
    getGlobalVolumeTool.name,
    getGlobalVolumeTool.config,
    instrumentMcpToolHandler(
      getGlobalVolumeTool.name,
      getGlobalVolumeTool.config.outputSchema,
      getGlobalVolumeTool.handler,
    ),
  );
  server.registerTool(
    getBusinessProfileTool.name,
    getBusinessProfileTool.config,
    instrumentMcpToolHandler(
      getBusinessProfileTool.name,
      getBusinessProfileTool.config.outputSchema,
      getBusinessProfileTool.handler,
    ),
  );
  server.registerTool(
    getBusinessReviewsTool.name,
    getBusinessReviewsTool.config,
    instrumentMcpToolHandler(
      getBusinessReviewsTool.name,
      getBusinessReviewsTool.config.outputSchema,
      getBusinessReviewsTool.handler,
    ),
  );
  server.registerTool(
    getAiSearchVolumeTool.name,
    getAiSearchVolumeTool.config,
    instrumentMcpToolHandler(
      getAiSearchVolumeTool.name,
      getAiSearchVolumeTool.config.outputSchema,
      getAiSearchVolumeTool.handler,
    ),
  );
  registerMarketIntelligenceTools(server);
}

// Brand-monitoring and domain-analytics research tools.
function registerMarketIntelligenceTools(server: McpServer) {
  server.registerTool(
    searchBrandMentionsTool.name,
    searchBrandMentionsTool.config,
    instrumentMcpToolHandler(
      searchBrandMentionsTool.name,
      searchBrandMentionsTool.config.outputSchema,
      searchBrandMentionsTool.handler,
    ),
  );
  server.registerTool(
    getBrandMentionSummaryTool.name,
    getBrandMentionSummaryTool.config,
    instrumentMcpToolHandler(
      getBrandMentionSummaryTool.name,
      getBrandMentionSummaryTool.config.outputSchema,
      getBrandMentionSummaryTool.handler,
    ),
  );
  server.registerTool(
    getBrandMentionTrendsTool.name,
    getBrandMentionTrendsTool.config,
    instrumentMcpToolHandler(
      getBrandMentionTrendsTool.name,
      getBrandMentionTrendsTool.config.outputSchema,
      getBrandMentionTrendsTool.handler,
    ),
  );
  server.registerTool(
    getDomainTechnologiesTool.name,
    getDomainTechnologiesTool.config,
    instrumentMcpToolHandler(
      getDomainTechnologiesTool.name,
      getDomainTechnologiesTool.config.outputSchema,
      getDomainTechnologiesTool.handler,
    ),
  );
  server.registerTool(
    getDomainWhoisTool.name,
    getDomainWhoisTool.config,
    instrumentMcpToolHandler(
      getDomainWhoisTool.name,
      getDomainWhoisTool.config.outputSchema,
      getDomainWhoisTool.handler,
    ),
  );
  server.registerTool(
    auditPageTool.name,
    auditPageTool.config,
    instrumentMcpToolHandler(
      auditPageTool.name,
      auditPageTool.config.outputSchema,
      auditPageTool.handler,
    ),
  );
}
